apiVersion: v1
kind: Service
metadata:
  name: server-side-discovery-and-service-a
spec:
  selector:
    app: server-side-discovery-and-service-a
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
  