services:

  services_registry:
    image: nawaphon2539/microservices-lab:self-registration.services-registry
    env_file:
      - services_registry/services-registry-vars.env
    ports:
      - "1001:8761"
    networks:
      default:

  service_a:
    image: nawaphon2539/microservices-lab:self-registration.services-a
    env_file:
      - serviceA/service-a-vars.env
    ports:
      - "1002:8080"
    networks:
      default:


networks:
  default:
