DATABASE_URL=jdbc:postgresql://localhost:5432/dummy
DATABASE_USERNAME=dummy
DATABASE_PASSWORD=dummy
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.initialization-fail-timeout=-1
spring.sql.init.mode=never
