services:
  order-service:
    image: nawaphon2539/microservices-lab:order-service
    ports:
      - "1000:8080"
    env_file:
      - order_service/order-service-vars.env
    networks:
      default:
        ipv4_address: 192.168.1.2
  customer-service:
    image: nawaphon2539/microservices-lab:customer-service
    ports:
      - "1001:8080"
    env_file:
      - customer_service/customer-service-vars.env
    networks:
      default:
        ipv4_address: 192.168.1.3
  database:
    image: nawaphon2539/microservices-lab:private-table-per-service
    env_file:
      - db/database-vars.env
    networks:
      default:
        ipv4_address: 192.168.1.4

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.1.0/29
          gateway: 192.168.1.1
