services:

  zookeeper:
    image: ubuntu/zookeeper:latest
    env_file:
      - zookeeper/zookeeper-vars.env
    networks:
      default:
        ipv4_address: 192.168.1.2

  kafka_0:
    image: ubuntu/kafka:latest
    command: [ "/etc/kafka/server.properties", "--override", "advertised.listeners=PLAINTEXT://192.168.1.3:9092" ]
    env_file:
      - kafka/kafka-vars.env
    ports:
      - "9092:9092"
    networks:
      default:
        ipv4_address: 192.168.1.3
    depends_on: [ zookeeper ]

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.1.0/29
          gateway: 192.168.1.1
