services:
  order-service:
    image: nawaphon2539/microservices-lab:shared-database.order-service
    ports:
      - "1000:8080"
    env_file:
      - services/order_service/order-service-vars.env
    networks:
      default:
        ipv4_address: 192.168.1.2
    depends_on: [ database ]
  customer-service:
    image: nawaphon2539/microservices-lab:shared-database.customer-service
    ports:
      - "1001:8080"
    env_file:
      - services/customer_service/customer-service-vars.env
    networks:
      default:
        ipv4_address: 192.168.1.3
    depends_on: [ database ]
  database:
    image: nawaphon2539/microservices-lab:shared-database
    env_file:
      - db/database-vars.env
    networks:
      default:
        ipv4_address: 192.168.1.4

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.1.0/29
          gateway: 192.168.1.1
