services:
  orders_database:
    image: postgres:latest
    env_file: ./order_service_database/order_service_database.env
    command: [ "postgres", "-c", "wal_level=logical" ]
    ports:
      - "5432:5432"
    networks:
      default:
        ipv4_address: 192.168.1.5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    volumes:
      - '/home/nawaphon/Documents/transactional_outbox_pattern/postgres_data:/var/lib/postgresql/data'

  zookeeper:
    image: ubuntu/zookeeper:latest
    env_file: ./zookeeper/zookeeper.env
    networks:
      default:
        ipv4_address: 192.168.1.2
    healthcheck:
      test: ['nc', '-z', 'localhost', '2181', '||', '-1']

  kafka:
    image: ubuntu/kafka:latest
    command: [ "/etc/kafka/server.properties", "--override", "advertised.listeners=PLAINTEXT://192.168.1.3:9092" ]
    env_file: ./kafka/kafka.env
    ports:
      - "9092:9092"
    networks:
      default:
        ipv4_address: 192.168.1.3
    depends_on:
      zookeeper:
        condition: service_healthy

  orders_database_debezium:
    image: quay.io/debezium/connect:latest
    env_file: ./order_service_debezium/order_service_debezium.env
    ports:
      - '8083:8083'
    networks:
      default:
        ipv4_address: 192.168.1.4
    depends_on:
      kafka:
        condition: service_healthy


networks:
  default:
    ipam:
      config:
        - subnet: 192.168.1.0/28
          gateway: 192.168.1.1
