services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Bangkok
    command: [ "postgres", "-c", "wal_level=logical" ]
    ports:
      - "5432:5432"
    networks:
      default:
        ipv4_address: 192.168.1.5
    volumes:
      - '/home/nawaphon/Documents/transactional_outbox_pattern/postgres_data:/var/lib/postgresql/data'

  zookeeper:
    image: ubuntu/zookeeper:latest
    environment:
      - TZ=Asia/Bangkok
    networks:
      default:
        ipv4_address: 192.168.1.2

  kafka:
    image: ubuntu/kafka:latest
    command: [ "/etc/kafka/server.properties", "--override", "advertised.listeners=PLAINTEXT://192.168.1.3:9092" ]
    environment:
      - TZ=Asia/Bangkok
      - ZOOKEEPER_HOST=zookeeper
    ports:
      - "9092:9092"
    networks:
      default:
        ipv4_address: 192.168.1.3
    depends_on: [ zookeeper ]

  debezium:
    image: quay.io/debezium/connect:latest
    environment:
      - CONFIG_STORAGE_TOPIC=debezium_configs
      - TZ=Asia/Bangkok
      - OFFSET_STORAGE_TOPIC=debezium_offsets
      - STATUS_STORAGE_TOPIC=debezium_statuses
      - BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - '8083:8083'
    networks:
      default:
        ipv4_address: 192.168.1.4
    depends_on: [ kafka ]


networks:
  default:
    ipam:
      config:
        - subnet: 192.168.1.0/28
          gateway: 192.168.1.1
