name: build_sub_project
author: nawaphon
description: build_sub_project
inputs:
  project_name:
    description: 'The name of the project to build'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run the Gradle package task for project named ${{ inputs.project_name }}
      run: ./gradlew ${{ format(':{0}:build', input.project_name) }} --scan
      shell: bash