name: docker build image

on:
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_SECRET }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build private-table-per-service.customer-service image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./database_per_services/private_table_per_service/customer_service/Dockerfile
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/microservices-lab:private-table-per-service.customer-service
      - name: Build private-table-per-service.order-service image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./database_per_services/private_table_per_service/order_service/Dockerfile
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/microservices-lab:private-table-per-service.order-service
      - name: Build private_table_per_service database image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./database_per_services/private_table_per_service/db/Dockerfile
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/microservices-lab:private-table-per-service
