name: docker build image

on:
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '11'
          architecture: x64
          distribution: 'corretto'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.1.0

      - name: Run the Gradle package task
        uses: gradle/gradle-build-action@v2.11.1
        with:
          arguments: build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build private-table-per-service.customer-service image
        uses: docker/build-push-action@v5
        with:
          context: ./database_per_services/private_table_per_service/customer_service
          file: ./database_per_services/private_table_per_service/customer_service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/microservices-lab:private-table-per-service.customer-service
      - name: Build private-table-per-service.order-service image
        uses: docker/build-push-action@v5
        with:
          context: ./database_per_services/private_table_per_service/order_service
          file: ./database_per_services/private_table_per_service/order_service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/microservices-lab:private-table-per-service.order-service
      - name: Build private_table_per_service database image
        uses: docker/build-push-action@v5
        with:
          context: ./database_per_services/private_table_per_service/db
          file: ./database_per_services/private_table_per_service/db/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/microservices-lab:private-table-per-service
