name: Everynight build

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  build-jar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image_name: private_table_per_service@customer_service
            path: |
              ./database_per_services/private_table_per_service/customer_service/build/libs/*.jar
              ./database_per_services/private_table_per_service/customer_service/*.env
              ./database_per_services/private_table_per_service/customer_service/Dockerfile

          - image_name: private_table_per_service@order_service
            path: |
              ./database_per_services/private_table_per_service/order_service/build/libs/*.jar
              ./database_per_services/private_table_per_service/order_service/*.env
              ./database_per_services/private_table_per_service/order_service/Dockerfile

          - image_name: private_table_per_service@db
            path: |
              ./database_per_services/private_table_per_service/db/*.env
              ./database_per_services/private_table_per_service/db/Dockerfile

          - image_name: shared_databases@customer_service
            path: |
              ./shared_database/customer_service/build/libs/*.jar
              ./shared_database/customer_service/*.env
              ./shared_database/customer_service/Dockerfile

          - image_name: shared_databases@order_service
            path: |
              ./shared_database/order_service/build/libs/*.jar
              ./shared_database/order_service/*.env
              ./shared_database/order_service/Dockerfile

          - image_name: shared_databases@db
            path: |
              ./shared_database/db/*.env
              ./shared_database/db/*.sh
              ./shared_database/db/Dockerfile

          - image_name: rest@sender
            path: |
              ./messaging/rest/sender/build/libs/*.jar
              ./messaging/rest/sender/*.env
              ./messaging/rest/sender/Dockerfile

          - image_name: rest@receiver
            path: |
              ./messaging/rest/receiver/build/libs/*.jar
              ./messaging/rest/receiver/*.env
              ./messaging/rest/receiver/Dockerfile

          - image_name: event_sourcing@consumer
            path: |
              ./messaging/event_sourcing/consumer/build/libs/*.jar
              ./messaging/event_sourcing/consumer/*.env
              ./messaging/event_sourcing/consumer/Dockerfile

          - image_name: event_sourcing@producer
            path: |
              ./messaging/event_sourcing/producer/build/libs/*.jar
              ./messaging/event_sourcing/producer/*.env
              ./messaging/event_sourcing/producer/Dockerfile

          - image_name: graphql@gateway
            path: |
              ./messaging/graphql/gateway/build/libs/*.jar
              ./messaging/graphql/gateway/*.env
              ./messaging/graphql/gateway/Dockerfile

          - image_name: circuit_breaker@proxy
            path: |
              ./circuit_breaker/proxy/build/libs/*.jar
              ./circuit_breaker/proxy/*.env
              ./circuit_breaker/proxy/Dockerfile

          - image_name: circuit_breaker@real_service
            path: |
              ./circuit_breaker/real_service/build/libs/*.jar
              ./circuit_breaker/real_service/*.env
              ./circuit_breaker/real_service/Dockerfile

          - image_name: service_registry@self_registration
            path: |
              ./self_registration/services_registry/*.env
              ./self_registration/services_registry/Dockerfile
              ./self_registration/services_registry/build/libs/*.jar

          - image_name: serviceA@self_registration
            path: |
              ./self_registration/serviceA/*.env
              ./self_registration/serviceA/Dockerfile
              ./self_registration/serviceA/build/libs/*.jar

          - image_name: serviceA@client_side_discovery
            path: |
              ./client_side_discovery/serviceA/*.env
              ./client_side_discovery/serviceA/Dockerfile
              ./client_side_discovery/serviceA/build/libs/*.jar

          - image_name: service_registry@client_side_discovery
            path: |
              ./client_side_discovery/services_registry/*.env
              ./client_side_discovery/services_registry/Dockerfile
              ./client_side_discovery/services_registry/build/libs/*.jar

          - image_name: client@client_side_discovery
            path: |
              ./client_side_discovery/client/*.env
              ./client_side_discovery/client/Dockerfile
              ./client_side_discovery/client/build/libs/*.jar

          - image_name: serviceA@server_side_discovery
            path: |
              ./server_side_discovery/serviceA/*.env
              ./server_side_discovery/serviceA/Dockerfile
              ./server_side_discovery/serviceA/build/libs/*.jar

          - image_name: order_service@transactional_outbox_pattern_transaction_log_tailing
            path: |
              ./transactional_outbox_pattern/transaction_log_tailing/order_service/*.env
              ./transactional_outbox_pattern/transaction_log_tailing/order_service/Dockerfile
              ./transactional_outbox_pattern/transaction_log_tailing/order_service/build/libs/*.jar

          - image_name: client@grpc
            path: |
              ./messaging/grpc/client/*.env
              ./messaging/grpc/client/Dockerfile
              ./messaging/grpc/client/build/libs/*.jar

          - image_name: server@grpc
            path: |
              ./messaging/grpc/server/*.env
              ./messaging/grpc/server/Dockerfile
              ./messaging/grpc/server/build/libs/*.jar

    steps:
      - name: checkout codebase
        uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'
          architecture: x64
          distribution: 'oracle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run the Gradle package task
        run: ./gradlew build

      - name: Upload ${{ matrix.image_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image_name }}
          path: ${{ matrix.path }}
  
  
  
  

  push-image-private_table_per_service-customer_service:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: private_table_per_service@customer_service
      image_name_for_docker_hub: private_table_per_service.customer_service
    secrets: inherit

  push-image-private_table_per_service-order-service:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: private_table_per_service@order-service
      image_name_for_docker_hub: private_table_per_service.order-service
    secrets: inherit

  push-image-shared_databases-customer_service:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: shared_database@customer_service
      image_name_for_docker_hub: shared_database.customer_service
    secrets: inherit

  push-image-shared_databases-order_service:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: shared_database@order_service
      image_name_for_docker_hub: shared_database.order_service
    secrets: inherit

  push-image-shared_databases-database:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: shared_database@db
      image_name_for_docker_hub: shared_database.db
    secrets: inherit

  push-image-rest-sender:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: rest@sender
      image_name_for_docker_hub: rest.sender
    secrets: inherit

  push-image-rest-receiver:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: rest@receiver
      image_name_for_docker_hub: rest.receiver
    secrets: inherit

  push-image-event_sourcing-consumer:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: event_sourcing@consumer
      image_name_for_docker_hub: event_sourcing.consumer
    secrets: inherit

  push-image-event_sourcing-producer:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: event_sourcing@producer
      image_name_for_docker_hub: event_sourcing.producer
    secrets: inherit

  push-image-graphql-gateway:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: graphql@gateway
      image_name_for_docker_hub: graphql.gateway
    secrets: inherit

  push-image-circuit_breaker-proxy:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: circuit_breaker@proxy
      image_name_for_docker_hub: circuit_breaker.proxy
    secrets: inherit

  push-image-circuit_breaker-real_service:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: circuit_breaker@real_service
      image_name_for_docker_hub: circuit_breaker.real_service
    secrets: inherit

  push-image-service-discovery-self-registration:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: service_registry@self_registration
      image_name_for_docker_hub: service_registry.self_registration
    secrets: inherit

  push-image-service-A-self-registration:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: serviceA@self_registration
      image_name_for_docker_hub: serviceA.self_registration
    secrets: inherit

  push-image-service-A-client-side-discovery:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: serviceA@client_side_discovery
      image_name_for_docker_hub: serviceA.client_side_discovery
    secrets: inherit

  push-image-client-client-side-discovery:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: client@client_side_discovery
      image_name_for_docker_hub: client.client_side_discovery
    secrets: inherit

  push-image-service-discovery-client-side-discovery:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: service_registry@client_side_discovery
      image_name_for_docker_hub: service_registry.client_side_discovery
    secrets: inherit

  push-image-service-A-server-side-discovery:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: serviceA@server_side_discovery
      image_name_for_docker_hub: serviceA.server_side_discovery
    secrets: inherit

  push-image-order-service-transactional-outbox-pattern:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: order_service@transactional_outbox_pattern
      image_name_for_docker_hub: order_service.transactional_outbox_pattern
    secrets: inherit

  push-image-client-grpc:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: client@grpc
      image_name_for_docker_hub: client.grpc
    secrets: inherit

  push-image-server-grpc:
    needs: build-jar
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: server@grpc
      image_name_for_docker_hub: server.grpc
    secrets: inherit