name: Everynight build

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  build-jars:
    runs-on: ubuntu-latest
    name: Build jar for ${{ matrix.image_name }}
    strategy:
      matrix: ${{ fromJSON(vars.MATRIX) }}

    steps:
      - name: Setup
        uses: ./.github/actions/setup_java_and_gradle

      - name: Run the Gradle package task
        run: ./gradlew build

      - name: Upload ${{ matrix.image_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image_name }}
          path: ${{ matrix.path }}
  
  
  
  

  push-images-to-docker-hub:
    needs: build-jars
    name: Push image ${{ matrix.image_name }}
    strategy:
      matrix: ${{ fromJSON(vars.MATRIX) }}
    uses: ./.github/workflows/every_night_push_image_into_docker_repository.yml
    with:
      image_name: ${{ matrix.image_name }}
      image_name_for_docker_hub: ${{ matrix.image_name_for_docker_hub }}
    secrets: inherit