name: Merge Request Build
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - 'main'
permissions:
  contents: read
jobs:
  build-check-for-merge-request:
    runs-on: ubuntu-latest
    steps:
      - name: checkout codebase
        uses: actions/checkout@v4

      - name: Setup tool
        uses: ./.github/actions/setup_tools

      - name: Build project
        uses: ./.github/actions/build_all
