name: Merge Request Build
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - 'main'
permissions:
  contents: read
jobs:
  build-check-for-merge-request:
    runs-on: ubuntu-latest
    steps:
      - name: checkout codebase
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup_java_and_gradle
