name: Build Spring boot microservice project before request to merge to main branch
run-name: running build for merge request
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - 'main'
jobs:
  build-check-for-merge-request:
    runs-on: ubuntu-latest
    steps:
      - name: checkout codebase
        uses: actions/checkout@v4

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '11'
          architecture: x64
          distribution: 'corretto'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run the Gradle package task
        run: ./gradlew build
