services:

  servicesRegistry:
    image: nawaphon2539/microservices-lab:client-side-discovery.services-registry
    env_file:
      - services_registry/services-registry-vars.env
    ports:
      - "1001:8761"
    networks:
      default:

  service_a:
    image: nawaphon2539/microservices-lab:client-side-discovery.serviceA
    env_file:
      - serviceA/service-a-vars.env
    ports:
      - "1002-1005:8080"
    networks:
      default:
    deploy:
      mode: replicated
      replicas: 4


networks:
  default:
