server.servlet.context-path=/self_registration/services_a

spring.mvc.apiversion.use.path-segment=0
spring.application.name=serviceA

eureka.client.service-url.defaultZone=${SERVICE_REGISTRY}

logging.level.root=${LOG_LEVEL:INFO}


